In [1]:
from ucimlrepo import fetch_ucirepo
from typing import Tuple, List
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import random

In [2]:
np.random.seed(42)
K_NUMBER = 9
TARGET_COLUMN_NAME = "class"
TEST_SIZE = 0.2
HOLDOUT_INDEXES_NUMBER = 20
FIG_SIZE = (10, 8)
IMAGE_FONT_SIZE = 20
RESOLUTION_POINTS = 500

In [3]:
iris = fetch_ucirepo(id=53)

X_iris = iris.data.features
y_iris = iris.data.targets

iris_df = pd.concat([X_iris, y_iris], axis="columns")

In [4]:
iris_df.head()

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
list(iris_df[TARGET_COLUMN_NAME].unique())

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

In [6]:
class_mapping = {"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}
iris_df[TARGET_COLUMN_NAME] = iris_df[TARGET_COLUMN_NAME].map(class_mapping)
iris_df[TARGET_COLUMN_NAME]

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: class, Length: 150, dtype: int64

In [7]:
iris_df[TARGET_COLUMN_NAME].unique()

array([0, 1, 2], dtype=int64)

In [8]:
from classifiers.bayesian_classifier import BayesianGaussianClassifier
from utils.classifier_utils import ClassifierUtils

knn_holdout_indexes = ClassifierUtils.create_multiple_holdout_indexes(
    df=iris_df, n_indexes=HOLDOUT_INDEXES_NUMBER, test_size=TEST_SIZE
)

knn_accuracy_list = []

for train_indexes, test_indexes in knn_holdout_indexes:
    X_train, y_train, X_test, y_test = ClassifierUtils.separate_train_test(
        df=iris_df,
        train_indexes=train_indexes,
        test_indexes=test_indexes,
        target_column_name=TARGET_COLUMN_NAME,
    )

    classifier = BayesianGaussianClassifier()
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test=X_test)

    accuracy = ClassifierUtils.calculate_accuracy(y_true=y_test, y_pred=y_pred)
    error_rate = ClassifierUtils.calculate_error_rate(y_true=y_test, y_pred=y_pred)

    confusion_matrix_result = ClassifierUtils.confusion_matrix(
        y_true=y_test, y_pred=y_pred
    )

    knn_accuracy_list.append(
        (
            accuracy,
            error_rate,
            train_indexes,
            test_indexes,
            y_pred,
            confusion_matrix_result,
        )
    )

df_results_knn = pd.DataFrame(
    knn_accuracy_list,
    columns=[
        "accuracy",
        "error_rate",
        "train_indexes",
        "test_indexes",
        "y_pred",
        "confusion_matrix",
    ],
)

df_results_knn

,accuracy,error_rate,train_indexes,test_indexes,y_pred,confusion_matrix
0,1.000000,0.000000,"[73, 18, 118, 78, 76, 31, 64, 141, 68, 82, 110...","[1, 129, 130, 140, 14, 144, 20, 21, 149, 37, 4...","[0, 2, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 1, ...","[[7, 0, 0], [0, 11, 0], [0, 0, 12]]"
1,0.900000,0.100000,"[84, 20, 45, 47, 149, 114, 144, 117, 9, 90, 14...","[128, 129, 2, 133, 138, 12, 140, 142, 143, 26,...","[2, 2, 0, 1, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, ...","[[9, 0, 0], [0, 6, 2], [0, 1, 12]]"
2,0.966667,0.033333,"[54, 71, 117, 30, 58, 81, 10, 64, 51, 28, 131,...","[129, 133, 134, 7, 135, 141, 145, 18, 146, 20,...","[2, 1, 2, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2, 0, 0, ...","[[10, 0, 0], [0, 5, 0], [0, 1, 14]]"
3,1.000000,0.000000,"[51, 101, 131, 129, 106, 121, 141, 105, 37, 12...","[0, 1, 3, 135, 9, 140, 15, 143, 146, 149, 22, ...","[0, 0, 0, 2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, ...","[[13, 0, 0], [0, 9, 0], [0, 0, 8]]"
4,0.966667,0.033333,"[120, 110, 123, 94, 6, 129, 76, 51, 82, 47, 13...","[0, 131, 5, 134, 136, 142, 144, 18, 24, 32, 35...","[0, 2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[10, 0, 0], [0, 8, 1], [0, 0, 11]]"
5,1.000000,0.000000,"[85, 30, 108, 125, 10, 123, 95, 144, 82, 104, ...","[2, 130, 131, 132, 135, 11, 146, 29, 37, 46, 4...","[0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, ...","[[6, 0, 0], [0, 12, 0], [0, 0, 12]]"
6,0.966667,0.033333,"[15, 99, 57, 133, 87, 41, 75, 47, 81, 97, 113,...","[129, 130, 3, 5, 138, 139, 140, 20, 25, 30, 32...","[2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, ...","[[8, 0, 0], [0, 11, 1], [0, 0, 10]]"
7,0.966667,0.033333,"[143, 138, 95, 100, 58, 3, 104, 93, 107, 120, ...","[129, 4, 136, 9, 14, 142, 147, 148, 149, 25, 2...","[2, 0, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, ...","[[10, 0, 0], [0, 7, 1], [0, 0, 12]]"
8,1.000000,0.000000,"[51, 12, 144, 118, 85, 74, 140, 48, 149, 78, 1...","[130, 134, 7, 135, 9, 138, 141, 147, 31, 33, 3...","[2, 2, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1, ...","[[6, 0, 0], [0, 14, 0], [0, 0, 10]]"
9,0.966667,0.033333,"[93, 27, 124, 126, 52, 21, 37, 117, 119, 5, 13...","[128, 130, 133, 11, 16, 145, 18, 24, 34, 38, 3...","[2, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[11, 0, 0], [0, 9, 0], [0, 1, 9]]"
10,1.000000,0.000000,"[89, 144, 0, 128, 63, 127, 45, 14, 148, 79, 13...","[2, 3, 4, 5, 134, 8, 143, 19, 34, 46, 49, 51, ...","[0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, ...","[[9, 0, 0], [0, 11, 0], [0, 0, 10]]"
11,0.966667,0.033333,"[132, 65, 36, 4, 39, 72, 128, 103, 101, 40, 13...","[1, 3, 131, 133, 6, 137, 138, 13, 14, 141, 144...","[0, 0, 2, 1, 0, 2, 2, 0, 0, 2, 2, 0, 2, 0, 0, ...","[[12, 0, 0], [0, 4, 0], [0, 1, 13]]"
12,0.933333,0.066667,"[85, 9, 66, 115, 45, 15, 10, 26, 46, 93, 64, 6...","[3, 131, 5, 6, 7, 8, 132, 133, 140, 142, 21, 4...","[0, 2, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 1, 1, ...","[[8, 0, 0], [0, 7, 2], [0, 0, 13]]"
13,1.000000,0.000000,"[94, 73, 112, 57, 71, 53, 31, 127, 108, 123, 1...","[0, 132, 5, 7, 9, 141, 143, 19, 27, 43, 48, 55...","[0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 1, 1, 1, ...","[[8, 0, 0], [0, 10, 0], [0, 0, 12]]"
14,1.000000,0.000000,"[144, 64, 91, 61, 19, 75, 58, 54, 5, 56, 142, ...","[132, 11, 139, 14, 145, 146, 20, 24, 25, 35, 3...","[2, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[12, 0, 0], [0, 8, 0], [0, 0, 10]]"
15,1.000000,0.000000,"[10, 70, 99, 58, 74, 39, 113, 18, 102, 117, 55...","[1, 2, 129, 4, 130, 7, 135, 137, 12, 144, 26, ...","[0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, ...","[[11, 0, 0], [0, 10, 0], [0, 0, 9]]"
16,0.966667,0.033333,"[53, 5, 66, 128, 68, 60, 69, 36, 87, 108, 2, 1...","[1, 129, 131, 4, 133, 9, 10, 11, 137, 140, 141...","[0, 2, 2, 0, 1, 0, 0, 0, 2, 2, 2, 0, 2, 0, 0, ...","[[11, 0, 0], [0, 10, 0], [0, 1, 8]]"
17,1.000000,0.000000,"[62, 78, 130, 116, 119, 5, 99, 47, 53, 120, 60...","[4, 134, 7, 137, 138, 142, 143, 27, 35, 37, 40...","[0, 2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, ...","[[7, 0, 0], [0, 10, 0], [0, 0, 13]]"
18,0.966667,0.033333,"[114, 67, 31, 61, 42, 141, 149, 87, 55, 95, 58...","[2, 3, 131, 137, 139, 13, 16, 144, 18, 19, 146...","[0, 0, 2, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, ...","[[12, 0, 0], [0, 6, 1], [0, 0, 11]]"
19,0.966667,0.033333,"[44, 113, 54, 110, 30, 102, 46, 101, 134, 33, ...","[130, 141, 142, 145, 147, 20, 149, 23, 27, 32,...","[2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, ...","[[5, 0, 0], [0, 11, 1], [0, 0, 13]]"